### ISSUE TITLE
Primer3 crashes with exit code 255 when installed via conda

### ISSUE THREAD

**Issue by sndrtj** [LUMC/prinia#1]
When installed via conda, the primer3 call ends with exit code 255. 
The output file will contain the following message 

> Error: thermodynamic approach chosen, but path to thermodynamic parameters not specified

This is due to conda installing the thermodynamic parameter configuration files in a non-standard location. The primer3 executable will look in two locations:

1. `/opt/primer3_config`
2. `./primer3_config`  

Conda installs those files in `$CONDA_ENV/share/primer3/primer3_config`. 

Debian-based systems on apt will actually install the files in `/etc/primer3_config`, but Debian has [pacthed](http://changelogs.ubuntu.com/changelogs/pool/universe/p/primer3/primer3_2.3.6-1/changelog) primer3 to look there as well. 

We can set an extra parameter `PRIMER_THERMODYNAMIC_PARAMETERS_PATH ` to force primer3 to find its thermodynamic parameter configuration files.

**Comment by sndrtj** [comment]
Was revolved in d24fc7101d422981947088a917fd48143b1478d7

**Comment by flacuchenta** [comment]
How to force primer3 to find its thermodynamic parameter configuration files?

**Comment by sndrtj** [comment]
In the latest version of prinia, you can set the path to the thermodynamic parameter configuration files with `--thermodynamic-params`. Does that solve your problem?

**Comment by flacuchenta** [comment]
Hi Sander,
Thank for you help.
No realy.
I can't to force primer3 to find the parameter configuration file. Again,
my output follow as:
"PRIMER_ERROR=thermodynamic approach chosen, but path to thermodynamic
parameters not specified "

Indicate than primer3 no find its parameters, yet.
I use centos in my PC, and i don't know how to fix its.
Specify, where to add the PATH ?
(PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/home/sbravo/miniconda2/share/primer3/primer3_config/)

Regards


ᐧ

**Comment by sndrtj** [comment]
Could you share the exact command you are running that generates the error message?

**Comment by flacuchenta** [comment]
Yes of course.
is: primer3_core <unigenes.fasta.p3in> unigenes.fasta.p3out
But, only the first sequence is executed, then in the file unigenes.fasta.p3out, the error message appears as previously said.

**Comment by sndrtj** [comment]
Prinia _uses_ primer3, this repository is not primer3 itself. The primer3 repo itself can be found [here](https://github.com/primer3-org/primer3)

That said, you have to set `PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/your/path/to/the/config/` _inside_ the input file, like so:

```
SEQUENCE_ID=your_sequence_name
SEQUENCE_TEMPLATE=your_sequence_template
SEQUENCE_TARGET=your_sequece_target
<lots and lots of other settings>
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/your/path/to/the/config_dir/
=
```

**Comment by flacuchenta** [comment]
Thanks for your help.
Finally, I can execute it.
Uninstall and re-install primer3 (without the anaconda package manager), and run it without problems.

my output now:

SEQUENCE_ID=...
SEQUENCE_TEMPLATE=......
PRIMER_PRODUCT_SIZE_RANGE=100-280
SEQUENCE_TARGET=120,16
PRIMER_MAX_END_STABILITY=250
PRIMER_LEFT_NUM_RETURNED=5
PRIMER_RIGHT_NUM_RETURNED=5
PRIMER_INTERNAL_NUM_RETURNED=0
PRIMER_PAIR_NUM_RETURNED=5
PRIMER_PAIR_0_PENALTY=2.145678
PRIMER_LEFT_0_PENALTY=2.036733
PRIMER_RIGHT_0_PENALTY=0.108945
PRIMER_LEFT_0_SEQUENCE=GCAAACCCCTCTGTTTAAACCC
PRIMER_RIGHT_0_SEQUENCE=GCAGGAGCTGGATGCAAAAC
PRIMER_LEFT_0=9,22
PRIMER_RIGHT_0=225,20
PRIMER_LEFT_0_TM=59.963
PRIMER_RIGHT_0_TM=60.109
PRIMER_LEFT_0_GC_PERCENT=50.000
PRIMER_RIGHT_0_GC_PERCENT=55.000
PRIMER_LEFT_0_SELF_ANY_TH=15.59
PRIMER_RIGHT_0_SELF_ANY_TH=9.00
PRIMER_LEFT_0_SELF_END_TH=0.00
PRIMER_RIGHT_0_SELF_END_TH=0.00
PRIMER_LEFT_0_HAIRPIN_TH=36.33
PRIMER_RIGHT_0_HAIRPIN_TH=45.94
PRIMER_LEFT_0_END_STABILITY=4.1100
PRIMER_RIGHT_0_END_STABILITY=2.4300
PRIMER_PAIR_0_COMPL_ANY_TH=5.14
PRIMER_PAIR_0_COMPL_END_TH=0.00
PRIMER_PAIR_0_PRODUCT_SIZE=217
PRIMER_PAIR_1_PENALTY=2.195555
PRIMER_LEFT_1_PENALTY=2.086610
PRIMER_RIGHT_1_PENALTY=0.108945
.....
